In [1]:
import torch

# Creating not so simple yet simple tensors: 
In the previous cases, we have given a list of our own data to create tensors. For instance a 2-D tensor can be created as: 

In [107]:
my_tensor = torch.tensor([[1,23],[5,36],[7,19]])
my_tensor

tensor([[ 1, 23],
        [ 5, 36],
        [ 7, 19]])

Here, we are going to look at some ways of creating tensors with random values and special values. These might be important for model-testing and a hundred other purposes that random numbers are used for.

We are going to use the following methods for creating tensors with random values:
* torch.rand(x,y)
* torch.rand_like(z)
* torch.randn(x,y)
* torch.randn_like(z)
* torch.randint(low, high, (x,y))
* torch.randint_like(z, low, high)
* torch.empty(x, y)<br /><br />

And, for tensors with some special values and settings we will use the following:
* torch.randperm(n)
* torch.ones(x,y)
* torch.ones_like(z)
* new_ones(x,y)
* torch.zeros(x,y)
* torch.zeros_like(z)
* torch.eye(n)
* torch.full((x,y), n)
* torch.full_like(z, n)
* torch.arange(low, high, step)

## Creating tensors with random values:

* **torch.rand(x,y)** - Returns a tensor with random numbers from a uniform distribution of shape (x,y).

In [53]:
a = torch.rand(3,5) #Can't override dtype here to torch.long.
a

tensor([[0.4941, 0.1790, 0.8202, 0.2417, 0.0051],
        [0.5462, 0.7419, 0.8478, 0.6188, 0.1538],
        [0.5898, 0.5122, 0.5139, 0.4814, 0.7223]])

* **torch.rand_like(z)** - Takes in the tensor z as argument and returns another tensor of values picked up from a distribution similar to that of z's distribution with the same shape as z.

In [58]:
like_a = torch.rand_like(a, dtype = torch.double) #..but we can override dtype to double.
like_a

tensor([[0.3830, 0.2998, 0.8216, 0.1905, 0.0302],
        [0.2867, 0.4144, 0.0774, 0.9531, 0.2947],
        [0.7728, 0.7527, 0.9572, 0.2799, 0.9857]], dtype=torch.float64)

* **torch.randn(x,y)** - Returns a tensor with random numbers from a normal distribution with standard deviation 1 and mean 0, of shape (x,y).

In [55]:
b = torch.randn(2,4, dtype = torch.double)
b

tensor([[ 0.8403, -0.3458,  0.5760,  1.1836],
        [ 1.7014, -1.7222, -2.4605,  0.9948]], dtype=torch.float64)

* **torch.randn_like(z)** - Takes in the tensor z as argument and returns another tensor of values picked up from a distribution similar to that of z's normal distribution with the same shape as z.


In [59]:
like_b = torch.randn_like(b)
like_b

tensor([[ 0.4594,  1.4441, -0.1403, -2.1724],
        [-0.1906, -0.1553,  0.5925, -0.5559]], dtype=torch.float64)

What if we use torch.randn_like() to generate a tensor like the tensor *a* which was used using torch.rand()?

In [60]:
is_like_a = torch.randn_like(a)
print(is_like_a)
print('\nis_like_a:')
print(is_like_a.type())
print(is_like_a.dtype)
print('\na:')
print(a.type())
print(a.dtype)

tensor([[-0.6490, -0.4780, -0.8137, -0.5156,  0.9069],
        [-0.2891, -0.1667, -1.6234, -1.4662, -0.2948],
        [ 0.9188, -0.6610, -1.2913,  1.7852, -1.3573]])

is_like_a:
torch.FloatTensor
torch.float32

a:
torch.FloatTensor
torch.float32


There probably is no difference in the type as expected.

* **torch.randint(low, high, (x,y))**- Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive) of shape (x,y). Providing the lower limit is optional (by default it is set to 0)

In [48]:
c = torch.randint(13,(4,8))
c

tensor([[ 9,  1, 11,  0,  3, 12,  8,  7],
        [ 4,  1,  7,  7,  2,  0,  7,  3],
        [ 7,  7,  0,  6,  2,  5,  6,  6],
        [11,  7, 11,  0,  7, 10,  3,  9]])

In [49]:
c1 = torch.randint(13,(4,8), dtype = torch.float) #We can override the dtype here as well.
c1

tensor([[10.,  1., 11., 12.,  8.,  4., 12.,  9.],
        [ 4.,  1.,  9.,  6.,  0., 10., 12.,  0.],
        [ 4.,  5., 11.,  9.,  6.,  3.,  1.,  0.],
        [ 7.,  9.,  4.,  5.,  0., 12.,  0.,  2.]])

* **torch.randint_like(z, low, high)**- Takes in the tensor z as argument and returns another tensor filled with random integers generated uniformly between low (inclusive and optional) and high (exclusive) with the same shape as z.

In [47]:
torch.randint_like(c, 3, 19)

tensor([[17., 13.,  9.,  8., 13.,  7., 15.,  8.],
        [11.,  9., 17., 16.,  5., 11., 18.,  4.],
        [12., 15.,  5.,  4., 10.,  7., 10.,  7.],
        [ 9., 18., 11., 15.,  7.,  6.,  8., 14.]])

* **torch.empty(x, y)**- Returns a tensor with uninitialized data (holds garbage values) of shape (x,y). The values are sampled from a broader range of distribution.

In [34]:
e = torch.empty(2,3)
e

tensor([[0.0000e+00, 6.4460e-44, 1.8754e+28],
        [5.1481e+22, 1.3424e-05, 1.2812e-11]])

## Creating tensors with some special values and settings:

* **torch.randperm(n)** - Returns a 1-D tensor filled with random permutation of integers from 0 to n - 1 of size n. 

In [32]:
d = torch.randperm(14)
d

tensor([ 5, 11,  0,  9,  3,  1,  8, 13,  4, 10, 12,  7,  2,  6])

* **torch.ones(x,y)**- Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.

In [40]:
f = torch.ones(2,3)
f

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
f.dtype

torch.float32

* **torch.ones_like(z)**- Returns a tensor filled with the scalar value 1, with the same shape and type as z.

In [41]:
like_f = torch.ones_like(f, dtype = torch.long) #Overriding the dtype
like_f

tensor([[1, 1, 1],
        [1, 1, 1]])

We can also use the **new_ones(x,y)** method along with an existing tensor to get a tensor filled with 1's of shape (x,y) with the dtype of the tensor used. 

In [62]:
ones_like_f = f.new_ones(4,2)
ones_like_f

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [61]:
ones_like_like_f = like_f.new_ones(4,2)
ones_like_like_f

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

* **torch.zeros(x,y)**- Returns a tensor filled with the scalar value 0, with the shape (x,y).

In [63]:
g = torch.zeros(3,2)
g

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

* **torch.zeros_like(z)**- Returns a tensor filled with the scalar value 0, with the same shape and type as z.

In [68]:
like_g = torch.zeros_like(g)
like_g

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

* **torch.eye(n)**- Returns a 2-D square tensor of size n, with ones on the diagonal and zeros elsewhere.

In [74]:
h = torch.eye(4, dtype = torch.long) #Default dtype is torch.float32
h

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

* **torch.full((x,y), n)**- Returns a tensor of shape (x,y) filled with n.

In [77]:
i = torch.full((3,6), 782)
i

tensor([[782., 782., 782., 782., 782., 782.],
        [782., 782., 782., 782., 782., 782.],
        [782., 782., 782., 782., 782., 782.]])

* **torch.full_like(z, n)**- Returns a tensor of the same shape as z filled with n.

In [81]:
like_i = torch.full_like(i, 44, dtype = torch.long) 
like_i

tensor([[44, 44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44, 44]])

* **torch.arange(low, high, step)**- Returns a tensor starting from low (inclusive) to high (exclusive) incremented by step steps.

In [100]:
j = torch.arange(5, -15, -2, dtype = torch.float32) #Overriding the dtype to torch.float32. Default is torch.long.
j

tensor([  5.,   3.,   1.,  -1.,  -3.,  -5.,  -7.,  -9., -11., -13.])

That's it for now. See you soon!