# Hello, Old Friends!

Converting a Torch tensor to a NumPy array or Pandas series(and vice versa) is a breeze. This gives PyTorch the ability to work within the Python ecosystem.<br />
The Torch tensor and NumPy array or Pandas series will share their underlying memory locations (if the Torch tensor is on CPU), and changing one will change the other.

In [2]:
import torch 
import numpy as np
import pandas as pd

## Converting a Torch tensor to a NumPy array:
We use the **tensor.numpy()** method for the same.

In [14]:
an_int_tensor = torch.ones(5, dtype = torch.long)
an_int_tensor

tensor([1, 1, 1, 1, 1])

In [22]:
to_numpy_arr_int = an_int_tensor.numpy()
to_numpy_arr_int

array([1, 1, 1, 1, 1], dtype=int64)

In [18]:
a_float_tensor = torch.randint(1,17,(2,3))
a_float_tensor

tensor([[ 3,  2,  4],
        [13, 15,  4]])

In [21]:
to_numpy_arr = a_float_tensor.numpy()
to_numpy_arr

array([[ 3,  2,  4],
       [13, 15,  4]], dtype=int64)

In [23]:
a_float_tensor.add_(10) 
#In place addition. More on add_() method later. 
#For now, just know the value passed in as the argument 
#within the add_() mehtod, will be added to each of the element of the tensor.
#This will also change tensor_to_numpy_arr.
print(f'an_float_tensor is now:\n{a_float_tensor}') 
print(f'\nAlso, to_numpy_arr has changed to:\n{to_numpy_arr}')

a_float_tensor is now:
tensor([[13, 12, 14],
        [23, 25, 14]])

Also, to_numpy_arr has changed to:
[[13 12 14]
 [23 25 14]]


## Converting a NumPy array to Torch tensor:
We use the **torch.from_numpy(n)** method to convert a NumPy array n to a torch tensor.

In [42]:
arr = np.array([5,4,3,2,1])
arr

array([5, 4, 3, 2, 1])

In [43]:
arr_to_tensor = torch.from_numpy(arr)
arr_to_tensor

tensor([5, 4, 3, 2, 1], dtype=torch.int32)

In [44]:
np.add(arr, [10]*5, out = arr) #Adding a list of five 10s to arr and storing it in arr.
print(f'arr is now:\n{arr}') 
print(f'\nAlso, arr_to_tensor has changed to:\n{arr_to_tensor}')

arr is now:
[15 14 13 12 11]

Also, arr_to_tensor has changed to:
tensor([15, 14, 13, 12, 11], dtype=torch.int32)


In [45]:
back_to_arr = arr_to_tensor.numpy()
back_to_arr

array([15, 14, 13, 12, 11])

In [46]:
print('Adding 100 to each element of back_to_arr...')
print(np.add(back_to_arr, [100]*5, out = back_to_arr))
print(f'\nAlso changes arr_to_tensor to:\n{arr_to_tensor}')
print(f'\nAnd changes the original array, arr to:\n{arr}')

Adding 100 to each element of back_to_arr...
[115 114 113 112 111]

Also changes arr_to_tensor to:
tensor([115, 114, 113, 112, 111], dtype=torch.int32)

And changes the original array, arr to:
[115 114 113 112 111]


## Converting a Pandas series to a Torch tensor:
We use the same old **torch.from_numpy(n.values)** method with the attribute *values* of a Pandas series n.

In [9]:
a_series = pd.Series([0.1,0.2,0.3,100])
a_series

0      0.1
1      0.2
2      0.3
3    100.0
dtype: float64

In [10]:
series_to_ndarr = a_series.values #Converts the series to a Numpy ndarray.
series_to_torch = torch.from_numpy(series_to_ndarr)
series_to_torch

tensor([  0.1000,   0.2000,   0.3000, 100.0000], dtype=torch.float64)

Note: The conversion can be done in one line as well by passing a_series.values as an argument to torch.from_numpy() (obviously, duh!).

In [11]:
print('Adding 10 to each of the elements in the tensor series_to_torch...')
series_to_torch.add_(10)

Adding 10 to each of the elements in the tensor series_to_torch...


tensor([ 10.1000,  10.2000,  10.3000, 110.0000], dtype=torch.float64)

In [12]:
print('Also changes the series a_series to:')
a_series

Also changes the series a_series to:


0     10.1
1     10.2
2     10.3
3    110.0
dtype: float64

In [13]:
print('And changes the series_to_ndarr to:')
series_to_ndarr

And changes the series_to_ndarr to:


array([ 10.1,  10.2,  10.3, 110. ])

## Converting a Torch tensor to a Pandas series:
We use **pd.Series(n)** method to convert the Torch tensor *n* to a Pandas series.

In [23]:
a_tensor = torch.randperm(8)
a_tensor

tensor([3, 0, 4, 2, 7, 6, 5, 1])

In [24]:
to_series = pd.Series(a_tensor)
to_series

0    3
1    0
2    4
3    2
4    7
5    6
6    5
7    1
dtype: int64

In [25]:
print('Adding 10 to each of the elements in the tensor a_tensor...')
a_tensor.add_(10)

tensor([13, 10, 14, 12, 17, 16, 15, 11])

In [26]:
print('Also changes the series to_series to:')
to_series

0    13
1    10
2    14
3    12
4    17
5    16
6    15
7    11
dtype: int64

That's all for now. See you soon. Happy practicing! =)