# 1D Tensors

Tensor- A mathematical object analogous to but more general than a vector, represented by an array of components that are functions of the coordinates of a space.

That was a copied definition straight from Google. In simple words, for now, you think of a tensor as an array of data. That's it.

**Import the gorgeous library:**

In [1]:
import torch

**Creating a simple tensor:**
<br />Casting the list into a tensor by using the torch.tensor constructor.

In [5]:
a_list = [7,6,5,8,9,12,13,-90]
simple_tensor = torch.tensor(a_list) 
simple_tensor

tensor([  7,   6,   5,   8,   9,  12,  13, -90])

**Acessing the data in a tensor:**<br />
We use indexing and slicing just like we do in case of a list.

In [11]:
print(f'The data at the last index value is: {simple_tensor[-1]}')
print(f'Slicing done from 2nd to 5th indices: {simple_tensor[2:6]}')
print(f'The third data in the slice [4:8] is: {simple_tensor[4:9][2]}')

The data at the last index value is: -90
Slicing done from 2nd to 5th indices: tensor([ 5,  8,  9, 12])
The third data in the slice [4:8] is: 13


**The *dtype* attribute:**<br />
The data type attribute *dtype* is used to find the type of *value stored within the tensor*.

In [13]:
print(f'The data within simple_tensor is of type {simple_tensor.dtype}.')

The data within simple_tensor is of type torch.int64.


**The *type()* method:** <br />
The *type()* method is used to find out the *type of the tensor*. 

In [14]:
print(f'simple_tensor is a {simple_tensor.type()} type tensor.')

simple_tensor is a torch.LongTensor type tensor.


**A float tensor:**

In [16]:
fl_tensor = torch.tensor([1.2,1.0,3.4,2,6.9])
print(f'Type of data in fl_tensor is: {fl_tensor.dtype}.')
print(f'fl_tensor is in fact, a {fl_tensor.type()}.')

Type of data in fl_tensor is: torch.float32.
fl_tensor is in fact, a torch.FloatTensor.


**Type casting a tensor:**<br />
We can specify the datatype of the data present within the tensor overriding the dtype attribute in the constructor.

In [20]:
am_i_float = torch.tensor([1.2,1.0,3.4,2,6.9], dtype = torch.int32)
print(f'Well, am_i_float contains {am_i_float.dtype} type of data and its data are {am_i_float}.')

Well, am_i_float contains torch.int32 type of data and its data are tensor([1, 1, 3, 2, 6], dtype=torch.int32).


In [23]:
am_i_int = torch.tensor(a_list, dtype = torch.float64)
print('Guess who just got converted to float? ;)')
print(f'am_i_int contains: {am_i_int}')

Guess who just got converted to float? ;)
am_i_int contains: tensor([  7.,   6.,   5.,   8.,   9.,  12.,  13., -90.], dtype=torch.float64)


**Explicitly creating tensors of a specific type:** <br />
By specifying the type of the tensor during its initialization.

In [24]:
i_want_a_float_tensor = torch.FloatTensor(a_list)
print(f'i_want_a_float_tensor contains {i_want_a_float_tensor}\
and is of type {i_want_a_float_tensor.type()}.')

i_want_a_float_tensor contains tensor([  7.,   6.,   5.,   8.,   9.,  12.,  13., -90.])and is of type torch.FloatTensor.


**Changing the type of a tensor:**<br /> 
By specifying the type needed as an argument for the type() method.

In [33]:
before = torch.tensor(a_list)
print(f'before is a {before.type()} type of tensor\n\
with values {before}\n\
whose data type is {before.dtype}.')
after = before.type(torch.FloatTensor)
print('\nTada!\n')
print(f'after became a {after.type()} type of tensor\nwith values {after}\n\
whose datastype is {after.dtype}!')

before is a torch.LongTensor type of tensor
with values tensor([  7,   6,   5,   8,   9,  12,  13, -90])
whose data type is torch.int64.

Tada!

after became a torch.FloatTensor type of tensor
with values tensor([  7.,   6.,   5.,   8.,   9.,  12.,  13., -90.])
whose datastype is torch.float32!


Also, worth noting, we can specify the data type of the values within the tensor as an argument to type() method. It more or less does the same stuff.

In [35]:
after_reboot = before.type(torch.float32)
print(f'after_reboot is also a {after_reboot.type()} type of tensor')
print(f'with values {after_reboot}')
print(f'whose data type is {after_reboot.dtype}.')

after_reboot is also a torch.FloatTensor type of tensor
with values tensor([  7.,   6.,   5.,   8.,   9.,  12.,  13., -90.])
whose data type is torch.float32.


**The *size()* and *ndimension()* methods:** <br />
* size()- Gives the number of elements present in the tensor.
* ndimension()- Gives the dimension of the tensor.

In [41]:
test_tensor = torch.tensor(a_list)
print(f'The test_tensor has values-\n{test_tensor},\n\
its size is {test_tensor.size()},\n\
and its dimension is {test_tensor.ndimension()}.')

The test_tensor has values-
tensor([  7,   6,   5,   8,   9,  12,  13, -90]),
its size is torch.Size([8]),
and its dimension is 1.


**The view() method:** <br />
In some cases, our neural networks may need 2D tensors as input while all we may have is a 1D tensor. In such cases, we would want to convert a 1D tensor to a 2D tensor which is exactly what we use the view() method for.<br />
*view(x,y)* would transform a tensor of any dimension to two dimensions having x rows and y columns. 

In [46]:
test_col = test_tensor.view(8,1)
print(f'Now, test_tensor is a 2D tensor with 8 rows and 1 column \
and it looks like:\n{test_col}')

Now, test_tensor is a 2D tensor with 8 rows and 1 column and it looks like:
tensor([[  7],
        [  6],
        [  5],
        [  8],
        [  9],
        [ 12],
        [ 13],
        [-90]])


If we do not know the number of rows or we do not want to specify it explicitly, we can pass in -1 as the first argument and the number of columns as the second argument.

In [51]:
print(f'If test_tensor were to have 4 columns, it will look like:')
test_tensor.view(-1,4)

If test_tensor were to have 4 columns, it will look like:


tensor([[  7,   6,   5,   8],
        [  9,  12,  13, -90]])

Let's see what happens when the number of columns is not a factor of the total number of elements present in the tesnsor.

In [50]:
test_tensor.view(-1,5)

RuntimeError: shape '[-1, 5]' is invalid for input of size 8

As expected, it throws an error.

**The *torch.is_tensor()* method:** <br />
It takes in one positional argument- the object that we wish to test for being a tensor or not- and returns a boolean value.  

In [73]:
torch.is_tensor(test_tensor)

True

In [74]:
torch.is_tensor(45)

False

but...

In [76]:
i_am_45 = torch.tensor(45)
torch.is_tensor(i_am_45)

True

For now, that is it! Next, we'll see how we can create tensors in different ways. 