## Some new methods to talk about:

Previously we saw how to bridge the gap between Torch tensors and Numpy arrays or Pandas series. <br />
That was fun. Let us now see some more interesting stuffs on Torch tensors and other methods that are provided by PyTorch to make our lives easy.<br />
Let's import the gorgeous package:

In [1]:
import torch

And, create a tensor with a sophisticated name:

In [2]:
i_am_a_tensor = torch.tensor([1,2,3])
i_am_a_tensor

tensor([1, 2, 3])

**The *item()* method:**<br />
It should not come to us as a shock now that the individual elements of a tensor is also a tensor (I was shocked, trust me). <br />

In [9]:
i_am_a_tensor[0]

tensor(1)

However, we might have the need of using the actual number that the tensor element is. The *item()* method helps us in doing just that. 

In [13]:
i_am_a_tensor[0].item()

1

In [11]:
type(i_am_a_tensor[0].item())

int

Also, keep in mind that only **one** element tensors at a time can be converted to a scalar value. So, if we do something like:

In [14]:
i_am_a_tensor.item()

ValueError: only one element tensors can be converted to Python scalars

It will throw an error.<be />
Just in case we were expecting a list to be returned using the *item()* method (since we actually casted a list of integers to the tensor i_am_a_tensor), there's no need to be disappointed. PyTorch (obviously) has a method for that!

**The *tolist()* method:**<br />
As the name suggests, this method is used to convert a Torch tensor to a list. 

In [8]:
now_i_am_a_list = i_am_a_tensor.tolist()
print(f'now_i_am_a_list is in fact a {type(now_i_am_a_list)} and contains {now_i_am_a_list}.')

now_i_am_a_list is in fact a <class 'list'> and contains [1, 2, 3]


## Indexing and slicing a tensor (yet again):

Just like a list in Python is mutable, a list casted to a Torch tensor is also mutable.

**Indexing:**<br />
Let us take a look at our old tensor once.

In [15]:
i_am_a_tensor

tensor([1, 2, 3])

In [17]:
i_am_a_tensor[0] = 100
i_am_a_tensor

tensor([100,   2,   3])

In [19]:
i_am_a_tensor[-1] = 300
i_am_a_tensor

tensor([100,   2, 300])

**Slicing:**<br />
Let us create a bigger tensor (again, with a sophisticated name):

In [29]:
a_big_tensor = torch.randperm(14)
a_big_tensor

tensor([12,  7, 10,  0, 13,  6,  4,  1,  8,  5, 11,  3,  2,  9])

In [30]:
a_slice = a_big_tensor[3:9]
a_slice

tensor([ 0, 13,  6,  4,  1,  8])

We can also change the values of a slice within a tensor: 

In [35]:
a_slice[2:5] = torch.ones(3)
a_slice

tensor([ 0, 13,  1,  1,  1,  8])

Done for the day, yes. <br /> 
I am going to watch Avengers- Endgame, now! <br />
Happy practicing!